name: testing
on: push

jobs:
  test_project:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run Django unit tests
      run:
      sudo apt install python3-pip
        pip3 install --user django
        python3 manage.py test